name: Publish SAB BACnet discovery docker image
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - main

jobs:
   
  publish_sab_discovery_docker:  
    runs-on: ubuntu-latest
    steps:       
      - name : Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID_ECR }}
          aws-secret-access-key: ${{ secrets.AWS_KEY_ECR }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v2
        with:
          context: ./src/   
          push: true
          platforms: linux/arm/v7
          file: src/Dockerfile
          tags: | 
            ${{ steps.login-ecr.outputs.registry }}/foobot/sab/gg_secure_tunneling:latest